name: Todo Pipeline

on:
  push:
    paths:
      - 'todo_infra/**'
  pull_request:
    paths:
      - 'todo_infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run script
        run: echo "todo_infra folder changed!"
